/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: imu_samples.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "imu_samples.pb-c.h"
void   app__udp_comm__imu_samples__init
                     (App__UdpComm__ImuSamples         *message)
{
  static const App__UdpComm__ImuSamples init_value = APP__UDP_COMM__IMU_SAMPLES__INIT;
  *message = init_value;
}
size_t app__udp_comm__imu_samples__get_packed_size
                     (const App__UdpComm__ImuSamples *message)
{
  assert(message->base.descriptor == &app__udp_comm__imu_samples__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t app__udp_comm__imu_samples__pack
                     (const App__UdpComm__ImuSamples *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &app__udp_comm__imu_samples__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t app__udp_comm__imu_samples__pack_to_buffer
                     (const App__UdpComm__ImuSamples *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &app__udp_comm__imu_samples__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
App__UdpComm__ImuSamples *
       app__udp_comm__imu_samples__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (App__UdpComm__ImuSamples *)
     protobuf_c_message_unpack (&app__udp_comm__imu_samples__descriptor,
                                allocator, len, data);
}
void   app__udp_comm__imu_samples__free_unpacked
                     (App__UdpComm__ImuSamples *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &app__udp_comm__imu_samples__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor app__udp_comm__imu_samples__field_descriptors[9] =
{
  {
    "time_of_validity_us",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(App__UdpComm__ImuSamples, time_of_validity_us),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamps",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(App__UdpComm__ImuSamples, n_timestamps),
    offsetof(App__UdpComm__ImuSamples, timestamps),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accel_x_mpss",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(App__UdpComm__ImuSamples, n_accel_x_mpss),
    offsetof(App__UdpComm__ImuSamples, accel_x_mpss),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accel_y_mpss",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(App__UdpComm__ImuSamples, n_accel_y_mpss),
    offsetof(App__UdpComm__ImuSamples, accel_y_mpss),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accel_z_mpss",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(App__UdpComm__ImuSamples, n_accel_z_mpss),
    offsetof(App__UdpComm__ImuSamples, accel_z_mpss),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_x_dps",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(App__UdpComm__ImuSamples, n_gyro_x_dps),
    offsetof(App__UdpComm__ImuSamples, gyro_x_dps),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_y_dps",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(App__UdpComm__ImuSamples, n_gyro_y_dps),
    offsetof(App__UdpComm__ImuSamples, gyro_y_dps),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_z_dps",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(App__UdpComm__ImuSamples, n_gyro_z_dps),
    offsetof(App__UdpComm__ImuSamples, gyro_z_dps),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temp_degc",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(App__UdpComm__ImuSamples, n_temp_degc),
    offsetof(App__UdpComm__ImuSamples, temp_degc),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned app__udp_comm__imu_samples__field_indices_by_name[] = {
  2,   /* field[2] = accel_x_mpss */
  3,   /* field[3] = accel_y_mpss */
  4,   /* field[4] = accel_z_mpss */
  5,   /* field[5] = gyro_x_dps */
  6,   /* field[6] = gyro_y_dps */
  7,   /* field[7] = gyro_z_dps */
  8,   /* field[8] = temp_degc */
  0,   /* field[0] = time_of_validity_us */
  1,   /* field[1] = timestamps */
};
static const ProtobufCIntRange app__udp_comm__imu_samples__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor app__udp_comm__imu_samples__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "app.udp_comm.ImuSamples",
  "ImuSamples",
  "App__UdpComm__ImuSamples",
  "app.udp_comm",
  sizeof(App__UdpComm__ImuSamples),
  9,
  app__udp_comm__imu_samples__field_descriptors,
  app__udp_comm__imu_samples__field_indices_by_name,
  1,  app__udp_comm__imu_samples__number_ranges,
  (ProtobufCMessageInit) app__udp_comm__imu_samples__init,
  NULL,NULL,NULL    /* reserved[123] */
};
